name: 📦🚀 Build Installer - Linux DEB AMD64

on:
  push:
    branches:
      - main
      - dev
      - 'release/**'
    tags:
      - '**'
  release:
    types: [published]
  pull_request:
    branches:
      - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/release/')) && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build:
    name: Linux amd64 DEB Installer
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      max-parallel: 4

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install build tools
      run: |
        apt-get -yq --no-install-suggests --no-install-recommends install\
          devscripts debhelper dput fakeroot
    
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: "^1.20"
    
    - name: Build archive
      run: go run build/ci.go debsrc
      env:
        GO111MODULE: on
    
    - name: Debug
      run: find .

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bpx-installers-linux-deb-intel
        path: ${{ github.workspace }}/*.deb

    - name: Upload release artifacts
      if: env.RELEASE == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload \
          $RELEASE_TAG \
          *.deb
